server:
  port: 8080

client:
  url: ${CLIENT_URL}
 
spring:
  application:
    name: toeic-practice-backend
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: Toeic
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${gmail}
    password: ${password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            
# Config jwt
## env var
toeic-practice-backend:
 security:
  authentication:
   jwt:
    # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
    base64-secret: ${JWT_SECRET}
    # Token is valid 24 hours
    token-validity-in-seconds: 86400
    # RefreshToken is valid 7 days
    refreshToken-validity-in-seconds: 604800

# Config azure
azure:
  storage:
    container:
      name: ${AZURE_STORAGE_CONTAINER_NAME}
    connection:
      string: ${AZURE_CONNECTION_STRING}