server:
  port: 8080

client:
  url: ${CLIENT_URL}
 
spring:
  application:
    name: toeic-practice-backend
  cache:
    type: redis
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DATABASE_NAME}
      auto-index-creation: true
    redis:
      host: redis
      port: 6379
      password: ${REDIS_PASSWORD}
      timeout: 60000
      lecttuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 2
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
            redirectUri: "${BASE_URL}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${gmail}
    password: ${password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            
# Config jwt
## env var
toeic-practice-backend:
 security:
  authentication:
   jwt:
    # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
    base64-secret: ${JWT_SECRET}
    # Token is valid 24 hours
    token-validity-in-seconds: 86400
    # RefreshToken is valid 7 days
    refreshToken-validity-in-seconds: 604800

# Config ChatGPT API
chatgpt:
  api:
    url: ${CHATGPT_URL}
    model: ${CHATGPT_MODEL}
    key: ${CHATGPT_API_KEY}

# Config azure
azure:
  url-resources: ${AZURE_URL_RESOURCES}
  storage:
    container:
      name: ${AZURE_STORAGE_CONTAINER_NAME}
    connection:
      string: ${AZURE_CONNECTION_STRING}

# api
api:
  prefix: /api/v1
  
# recommender service interaction
recommender:
  service:
    url: ${RECOMMENDER_SERVICE_URL}